services:
  mysql:
    image: mysql
    container_name: mysql-orders
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orders
      MYSQL_PASSWORD: root
      MYSQL_INITDB_SQL: /docker-entrypoint-initdb.d/init.sql
    ports:
      - 3306:3306
    volumes:
      - ./sql:/docker-entrypoint-initdb.d

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest